=== guyjin/old_marsbase/mars/marbasenavmenu.dtd
<!ELEMENT SubURL (#PCDATA)>
<!ELEMENT HeadingURL (#PCDATA)>
<!ELEMENT MenuEntry (#PCDATA | HeadingTitle | HeadingURL | SubHeading)*>
<!ELEMENT SubTitle (#PCDATA)>
<!ELEMENT HeadingTitle (#PCDATA)>
<!ELEMENT SubHeading (#PCDATA | SubTitle | SubURL)*>
<!ELEMENT NavMenu (#PCDATA | MenuEntry)*>

=== guyjin/old_marsbase/mars/marbasenavmenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NavMenu SYSTEM "marbasenavmenu.dtd">
<?xml-stylesheet type="text/xsl" href="marsnavmenu.xsl"?>
<NavMenu>
    <MenuEntry>
        <HeadingTitle>home</HeadingTitle>
        <HeadingURL>/</HeadingURL>
        <SubHeading>
            <SubTitle>notes</SubTitle>
            <SubURL>/notes/</SubURL>
        </SubHeading>
    </MenuEntry>
    <MenuEntry>
        <HeadingTitle>mecha</HeadingTitle>
        <HeadingURL>/mecha/</HeadingURL>
        <SubHeading>
            <SubTitle>arapahoe</SubTitle>
            <SubURL>/mecha/arapahoe/</SubURL>
        </SubHeading>
        <SubHeading>
            <SubTitle>copperhead</SubTitle>
            <SubURL>/mecha/copperhead/</SubURL>
        </SubHeading>
    </MenuEntry>
    <MenuEntry>
        <HeadingTitle>ground</HeadingTitle>
        <HeadingURL>/ground/</HeadingURL>
        <SubHeading>
            <SubTitle>ranger</SubTitle>
            <SubURL>/ground/ranger/</SubURL>
        </SubHeading>
    </MenuEntry>
    <MenuEntry>
        <HeadingTitle>air</HeadingTitle>
        <HeadingURL>/air/</HeadingURL>
        <SubHeading>
            <SubTitle>dragonfly</SubTitle>
            <SubURL>/air/dragonfly/</SubURL>
        </SubHeading>
    </MenuEntry>
</NavMenu>
